"""ORAGAI Control Plane & Governance Package.

Specification: docs/plans/P13_FINAL_ORAGAI_TARGET_ARCHITECTURE_SPECIFICATION.md
"""

from __future__ import annotations

from orchestrator.governance.fsm import (
    CompletionDecision,
    CompletionStatus,
    EventType,
    FSMContext,
    FSMGuards,
    FSMState,
    GuardedFSMEngine,
    PipelineEvent,
    StateTransition,
    TaskTruthSemanticQueries,
    TransitionEvent,
    TransitionMatrix,
    TransitionResult,
    TransitionRule,
    evaluate_task_completion,
)
from orchestrator.governance.resource import (
    AdaptiveBudgetAllocator,
    AdaptiveCircuitBreaker,
    CircuitBreakerDecision,
    CircuitState,
    ComplexityEstimator,
    MonetaryCircuitBreaker,
    PhaseBudgetProfile,
    ResourceExhaustionReason,
    ResourceGovernorConfig,
    ResourcePhase,
    TurnBudgetResult,
    compute_task_complexity,
)
from orchestrator.governance.stagnation import (
    CyclePattern,
    MutationStrategyType,
    OscillationDetector,
    ProgressHealth,
    ProgressVelocityMetrics,
    RecoveryActionType,
    RecoveryDecision,
    RecoveryOrchestrator,
    SemanticProgressTracker,
    StateFingerprint,
    StrategyMutationDirective,
    StrategyMutator,
)
from orchestrator.governance.gates import (
    CompletionGate,
    verify_mandatory_criteria_satisfied,
)

__all__ = [
    "GuardedFSMEngine",
    "FSMContext",
    "FSMState",
    "EventType",
    "TransitionEvent",
    "PipelineEvent",
    "TransitionRule",
    "StateTransition",
    "TransitionResult",
    "TransitionMatrix",
    "CompletionDecision",
    "CompletionStatus",
    "FSMGuards",
    "TaskTruthSemanticQueries",
    "evaluate_task_completion",
    "ComplexityEstimator",
    "compute_task_complexity",
    "AdaptiveBudgetAllocator",
    "PhaseBudgetProfile",
    "ResourceGovernorConfig",
    "ResourcePhase",
    "TurnBudgetResult",
    "MonetaryCircuitBreaker",
    "AdaptiveCircuitBreaker",
    "CircuitBreakerDecision",
    "CircuitState",
    "ResourceExhaustionReason",
    "SemanticProgressTracker",
    "ProgressHealth",
    "ProgressVelocityMetrics",
    "StateFingerprint",
    "CyclePattern",
    "OscillationDetector",
    "RecoveryOrchestrator",
    "StrategyMutator",
    "MutationStrategyType",
    "RecoveryActionType",
    "RecoveryDecision",
    "StrategyMutationDirective",
    "CompletionGate",
    "verify_mandatory_criteria_satisfied",
]
