"""Governance Policy and Task Budget Profiles for Adaptive Iteration Governance."""

from __future__ import annotations

from typing import Dict
from orchestrator.governance.models import TaskBudgetProfile, TaskCategory


DEFAULT_TASK_PROFILES: Dict[TaskCategory, TaskBudgetProfile] = {
    TaskCategory.ARCHITECTURE: TaskBudgetProfile(
        category=TaskCategory.ARCHITECTURE,
        initial_turns=12,
        min_turns=5,
        max_extension_turns=6,
        max_total_ceiling_turns=25,
        checkpoint_interval=4,
        exploration_phase_turns=8,
        expected_tools=["workspace_file", "workspace_terminal"],
    ),
    TaskCategory.IMPLEMENTATION: TaskBudgetProfile(
        category=TaskCategory.IMPLEMENTATION,
        initial_turns=20,
        min_turns=10,
        max_extension_turns=10,
        max_total_ceiling_turns=50,
        checkpoint_interval=5,
        exploration_phase_turns=6,
        expected_tools=["workspace_file", "workspace_terminal"],
    ),
    TaskCategory.DEBUGGING: TaskBudgetProfile(
        category=TaskCategory.DEBUGGING,
        initial_turns=18,
        min_turns=8,
        max_extension_turns=8,
        max_total_ceiling_turns=40,
        checkpoint_interval=4,
        exploration_phase_turns=5,
        expected_tools=["workspace_terminal", "workspace_file"],
    ),
    TaskCategory.TESTING: TaskBudgetProfile(
        category=TaskCategory.TESTING,
        initial_turns=15,
        min_turns=6,
        max_extension_turns=8,
        max_total_ceiling_turns=35,
        checkpoint_interval=5,
        exploration_phase_turns=5,
        expected_tools=["workspace_terminal", "workspace_file"],
    ),
    TaskCategory.REVIEW: TaskBudgetProfile(
        category=TaskCategory.REVIEW,
        initial_turns=10,
        min_turns=4,
        max_extension_turns=5,
        max_total_ceiling_turns=20,
        checkpoint_interval=4,
        exploration_phase_turns=6,
        expected_tools=["workspace_file"],
    ),
    TaskCategory.AUDIT: TaskBudgetProfile(
        category=TaskCategory.AUDIT,
        initial_turns=25,
        min_turns=12,
        max_extension_turns=10,
        max_total_ceiling_turns=50,
        checkpoint_interval=6,
        exploration_phase_turns=10,
        expected_tools=["workspace_file", "workspace_terminal"],
    ),
    TaskCategory.REFACTORING: TaskBudgetProfile(
        category=TaskCategory.REFACTORING,
        initial_turns=20,
        min_turns=8,
        max_extension_turns=10,
        max_total_ceiling_turns=45,
        checkpoint_interval=5,
        exploration_phase_turns=6,
        expected_tools=["workspace_file", "workspace_terminal"],
    ),
    TaskCategory.RESEARCH: TaskBudgetProfile(
        category=TaskCategory.RESEARCH,
        initial_turns=12,
        min_turns=5,
        max_extension_turns=6,
        max_total_ceiling_turns=25,
        checkpoint_interval=4,
        exploration_phase_turns=8,
        expected_tools=["workspace_file"],
    ),
    TaskCategory.DOCUMENTATION: TaskBudgetProfile(
        category=TaskCategory.DOCUMENTATION,
        initial_turns=12,
        min_turns=5,
        max_extension_turns=6,
        max_total_ceiling_turns=25,
        checkpoint_interval=4,
        exploration_phase_turns=5,
        expected_tools=["workspace_file"],
    ),
    TaskCategory.SECURITY: TaskBudgetProfile(
        category=TaskCategory.SECURITY,
        initial_turns=20,
        min_turns=8,
        max_extension_turns=8,
        max_total_ceiling_turns=40,
        checkpoint_interval=5,
        exploration_phase_turns=8,
        expected_tools=["workspace_file", "workspace_terminal"],
    ),
    TaskCategory.CODE_GENERATION: TaskBudgetProfile(
        category=TaskCategory.CODE_GENERATION,
        initial_turns=15,
        min_turns=8,
        max_extension_turns=8,
        max_total_ceiling_turns=35,
        checkpoint_interval=5,
        exploration_phase_turns=4,
        expected_tools=["workspace_file"],
    ),
}
